# Generated by Django 4.0.6 on 2025-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaas',
            name='brandy',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
