# Generated by Django 4.0.6 on 2025-09-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_bidhaas_brandy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhaas',
            name='brandy',
        ),
    ]
